from rest_framework.routers import DefaultRouter
from django.urls import path, include

from . import views
app_name = "bookings"

router = DefaultRouter()
router.register(r"reservations", views.ReservationViewSet, basename="reservation")
router.register(r"reservation-payment", views.ReservationPaymentViewSet, basename="ReservationPayment")
router.register(
    r"reservation-service", views.ReservationServiceViewSet, basename="reservation-service"
)

urlpatterns = [
    # viewsets
    # The line `path('', include(router.urls)),` in the urlpatterns list is including the URLs
    # generated by the DefaultRouter for the viewsets registered with it.
    path("", include(router.urls)),
    path("pricing-config/", views.ReservationPricingConfigAPIView.as_view(), name="reservation-pricing-config"),
    # api route for UserReservationsAPIView
    path(
        "user/<uuid:user_id>/reservations/",
        views.UserReservationsAPIView.as_view(),
        name="user-reservations",
    ),
    # api route for VehicleReservationsAPIView
    path(
        "vehicle/<uuid:vehicle_id>/reservations/",
        views.VehicleReservationsAPIView.as_view(),
        name="vehicle-reservations",
    ),
    # api route for StatusReservationsAPIView
    path(
        "status/<str:status>/reservations/",
        views.StatusReservationsAPIView.as_view(),
        name="status-reservations",
    ),
    # api route for ActiveReservationsAPIView
    path(
        "active/reservations/",
        views.ActiveReservationsAPIView.as_view(),
        name="active-reservations",
    ),
    # api route for CompletedReservationsAPIView
    path(
        "completed/reservations/",
        views.CompletedReservationsAPIView.as_view(),
        name="completed-reservations",
    ),
    # api route for DateRangeReservationsAPIView
    path(
        "date-range/reservations/",
        views.DateRangeReservationsAPIView.as_view(),
        name="date-range-reservations",
    ),
    # api route for TotalReservationsCountAPIView
    path(
        "total-count/reservations/",
        views.TotalReservationsCountAPIView.as_view(),
        name="total-reservations-count",
    ),
    # api route for ChauffeurReservationsAPIView
    path(
        "with-chauffeur/reservations/",
        views.ChauffeurReservationsAPIView.as_view(),
        name="with-chauffeur-reservations",
    ),
    # api route for WithoutChauffeurReservationsAPIView
    path(
        "without-chauffeur/reservations/",
        views.WithoutChauffeurReservationsAPIView.as_view(),
        name="without-chauffeur-reservations",
    ),
    # api route for PickupLocationReservationsAPIView
    path(
        "pickup-location/<str:location>/reservations/",
        views.PickupLocationReservationsAPIView.as_view(),
        name="pickup-location-reservations",
    ),
    # api route for DropoffLocationReservationsAPIView
    path(
        "dropoff-location/<str:location>/reservations/",
        views.DropoffLocationReservationsAPIView.as_view(),
        name="dropoff-location-reservations",
    ),
    # api route for MinTotalAmountReservationsAPIView
    path(
        "min-total-amount/reservations/",
        views.MinTotalAmountReservationsAPIView.as_view(),
        name="min-total-amount-reservations",
    ),
    # api route for MaxTotalAmountReservationsAPIView
    path(
        "max-total-amount/reservations/",
        views.MaxTotalAmountReservationsAPIView.as_view(),
        name="max-total-amount-reservations",
    ),
    # api route for MinTotalDaysReservationsAPIView
    path(
        "min-total-days/reservations/",
        views.MinTotalDaysReservationsAPIView.as_view(),
        name="min-total-days-reservations",
    ),
    # api route for ReservationServiceByReservationAPIView
    path(
        "reservation/<uuid:reservation_id>/services/",
        views.ReservationServiceByReservationAPIView.as_view(),
        name="reservation-service-by-reservation",
    ),
    # api route for ReservationServiceByNameAPIView
    path(
        "service-name/<str:service_name>/services/",
        views.ReservationServiceByNameAPIView.as_view(),
        name="reservation-service-by-name",
    ),
    # api route for ReservationServiceByPriceRangeAPIView
    path(
        "service-price-range/services/",
        views.ReservationServiceByPriceRangeAPIView.as_view(),
        name="reservation-service-by-price-range",
    ),
    # api route for ReservationServiceByMinQuantityAPIView
    path(
        "min-quantity/services/",
        views.ReservationServiceByMinQuantityAPIView.as_view(),
        name="reservation-service-by-min-quantity",
    ),
    # api route for ReservationServiceByMaxQuantityAPIView
    path(
        "max-quantity/services/",
        views.ReservationServiceByMaxQuantityAPIView.as_view(),
        name="reservation-service-by-max-quantity",
    ),
    # admin statistics endpoints
    path(
        "statistics/",
        views.ReservationStatisticsAPIView.as_view(),
        name="reservation-statistics",
    ),
    path(
        "daily-income/",
        views.DailyIncomeAPIView.as_view(),
        name="reservation-daily-income",
    ),
]


# graphique
urlpatterns += [
    path("stats/day/", views.ReservationStatsViewSet.as_view({"get": "day"})),
    path("stats/week/", views.ReservationStatsViewSet.as_view({"get": "week"})),
    path("stats/month/", views.ReservationStatsViewSet.as_view({"get": "month"})),
    path("owner/<str:owner_id>/reservations/", views.OwnerVehicleReservationsAPIView.as_view(), name="owner-vehicle-reservations"),
]

# reservation email
urlpatterns += [
    path("<uuid:reservation_id>/and/<uuid:payment_id>/payment/", views.reservation_payment_page, name="reservation_payment_page"),
    path("payment/submit/", views.submit_reservation_payment, name="submit_payment"),
    # API
    path("send-link-payment/", views.send_link_payment, name="api_send_link_payment"),
    # path("booking/<uuid:reservation_id>/", views.booking_detail, name="booking_detail"),

]
